### ISSUE TITLE
Extending supportedLanguages

### ISSUE THREAD

**Issue by mgiesen** [mgiesen/Image-Comments#3]

**Comment by SeppBerkner** [comment]
Hi Maximilian,

It seems you have the only extension out there to add images to code! Just wondering if you are still working on this feature as I would love to show images of intermediate steps in my SQL-based spatial data transformation. Because different geometries are created in these steps it would be easier to show an image of a resulting image in every step rather than writing long texts to describe the features of these geometries. Is an addition of SQL possible?

**Comment by mgiesen** [comment]
Hi @SeppBerkner 

I released 0.6.0 for you with support for sql files. 

Cheers
Max

**Comment by SeppBerkner** [comment]
Hi @mgiesen, thanks so much for the quick extention! I will give it a try!
